"""add class settings table

Revision ID: 38fa0e9e717d
Revises: ff60d5c04b9b
Create Date: 2025-06-02 15:55:27.037239

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '38fa0e9e717d'
down_revision = 'ff60d5c04b9b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CAIDATLOPHOC',
    sa.Column('maLopHoc', sa.BigInteger(), nullable=False),
    sa.Column('maxStudents', sa.Integer(), nullable=False),
    sa.Column('allowSelfEnroll', sa.Boolean(), nullable=False),
    sa.Column('requireApproval', sa.Boolean(), nullable=False),
    sa.Column('emailNotifications', sa.Boolean(), nullable=False),
    sa.Column('smsNotifications', sa.Boolean(), nullable=False),
    sa.Column('parentNotifications', sa.Boolean(), nullable=False),
    sa.Column('autoGrading', sa.Boolean(), nullable=False),
    sa.Column('passingScore', sa.Float(), nullable=False),
    sa.Column('retakeAllowed', sa.Boolean(), nullable=False),
    sa.Column('maxRetakeAttempts', sa.Integer(), nullable=False),
    sa.Column('showStudentList', sa.Boolean(), nullable=False),
    sa.Column('showScores', sa.Boolean(), nullable=False),
    sa.Column('allowStudentComments', sa.Boolean(), nullable=False),
    sa.Column('dataRetentionDays', sa.Integer(), nullable=False),
    sa.Column('backupFrequency', sa.String(length=20), nullable=False),
    sa.Column('auditLogging', sa.Boolean(), nullable=False),
    sa.Column('thoiGianTao', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('thoiGianCapNhat', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['maLopHoc'], ['LOPHOC.maLopHoc'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('maLopHoc')
    )
    op.create_index(op.f('ix_CAIDATLOPHOC_maLopHoc'), 'CAIDATLOPHOC', ['maLopHoc'], unique=False)
    op.alter_column('BAIKIEMTRA', 'maToChuc',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('BAIKIEMTRA', 'maNguoiTao',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('BAIKIEMTRA', 'maMauPhieu',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('BAIKIEMTRA', 'laDeTongHop',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('BAIKIEMTRA', 'trangThai',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'nhap'::character varying"))
    op.alter_column('BAIKIEMTRA', 'thoiGianTao',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('BAIKIEMTRA', 'thoiGianCapNhat',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index('idx_bkt_author', table_name='BAIKIEMTRA')
    op.drop_index('idx_bkt_org', table_name='BAIKIEMTRA')
    op.create_index(op.f('ix_BAIKIEMTRA_maBaiKiemTra'), 'BAIKIEMTRA', ['maBaiKiemTra'], unique=False)
    op.create_index(op.f('ix_BAIKIEMTRA_maMauPhieu'), 'BAIKIEMTRA', ['maMauPhieu'], unique=False)
    op.create_index(op.f('ix_BAIKIEMTRA_maNguoiTao'), 'BAIKIEMTRA', ['maNguoiTao'], unique=False)
    op.create_index(op.f('ix_BAIKIEMTRA_maToChuc'), 'BAIKIEMTRA', ['maToChuc'], unique=False)
    op.drop_constraint('BAIKIEMTRA_maMauPhieu_fkey', 'BAIKIEMTRA', type_='foreignkey')
    op.drop_constraint('BAIKIEMTRA_maToChuc_fkey', 'BAIKIEMTRA', type_='foreignkey')
    op.drop_constraint('BAIKIEMTRA_maNguoiTao_fkey', 'BAIKIEMTRA', type_='foreignkey')
    op.create_foreign_key(None, 'BAIKIEMTRA', 'NGUOIDUNG', ['maNguoiTao'], ['maNguoiDung'])
    op.create_foreign_key(None, 'BAIKIEMTRA', 'MAUPHIEUTRALOI', ['maMauPhieu'], ['maMauPhieu'])
    op.create_foreign_key(None, 'BAIKIEMTRA', 'TOCHUC', ['maToChuc'], ['maToChuc'])
    op.alter_column('BAIKIEMTRA_LOPHOC', 'maBaiKiemTra',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('BAIKIEMTRA_LOPHOC', 'maLopHoc',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('BAIKIEMTRA_LOPHOC', 'thoiGianTao',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint('uq_bkt_lop', 'BAIKIEMTRA_LOPHOC', type_='unique')
    op.create_index(op.f('ix_BAIKIEMTRA_LOPHOC_id'), 'BAIKIEMTRA_LOPHOC', ['id'], unique=False)
    op.create_index(op.f('ix_BAIKIEMTRA_LOPHOC_maBaiKiemTra'), 'BAIKIEMTRA_LOPHOC', ['maBaiKiemTra'], unique=False)
    op.create_index(op.f('ix_BAIKIEMTRA_LOPHOC_maLopHoc'), 'BAIKIEMTRA_LOPHOC', ['maLopHoc'], unique=False)
    op.create_unique_constraint('uq_baikiemtra_lophoc', 'BAIKIEMTRA_LOPHOC', ['maBaiKiemTra', 'maLopHoc'])
    op.alter_column('CAIDAT', 'maToChuc',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('CAIDAT', 'thoiGianTao',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('CAIDAT', 'thoiGianCapNhat',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint('uq_caidat_org_key', 'CAIDAT', type_='unique')
    op.create_index(op.f('ix_CAIDAT_maCaiDat'), 'CAIDAT', ['maCaiDat'], unique=False)
    op.create_index(op.f('ix_CAIDAT_maToChuc'), 'CAIDAT', ['maToChuc'], unique=False)
    op.create_unique_constraint('uq_caidat_matochuc_tukhoa', 'CAIDAT', ['maToChuc', 'tuKhoa'])
    op.alter_column('DAPAN', 'maBaiKiemTra',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('DAPAN', 'thoiGianTao',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('DAPAN', 'thoiGianCapNhat',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint('DAPAN_maBaiKiemTra_key', 'DAPAN', type_='unique')
    op.create_index(op.f('ix_DAPAN_maBaiKiemTra'), 'DAPAN', ['maBaiKiemTra'], unique=True)
    op.create_index(op.f('ix_DAPAN_maDapAn'), 'DAPAN', ['maDapAn'], unique=False)
    op.alter_column('HOCSINH', 'maLopHoc',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('HOCSINH', 'trangThai',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('HOCSINH', 'thoiGianTao',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('HOCSINH', 'thoiGianCapNhat',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index('idx_hocsinh_lop', table_name='HOCSINH')
    op.drop_constraint('uq_hocsinh_code_lop', 'HOCSINH', type_='unique')
    op.create_index(op.f('ix_HOCSINH_maHocSinh'), 'HOCSINH', ['maHocSinh'], unique=False)
    op.create_index(op.f('ix_HOCSINH_maHocSinhTruong'), 'HOCSINH', ['maHocSinhTruong'], unique=False)
    op.create_index(op.f('ix_HOCSINH_maLopHoc'), 'HOCSINH', ['maLopHoc'], unique=False)
    op.create_unique_constraint('uq_hocsinh_mahocsinhtruong_malophoc', 'HOCSINH', ['maHocSinhTruong', 'maLopHoc'])
    op.drop_constraint('HOCSINH_maLopHoc_fkey', 'HOCSINH', type_='foreignkey')
    op.create_foreign_key(None, 'HOCSINH', 'LOPHOC', ['maLopHoc'], ['maLopHoc'])
    op.alter_column('KETQUA', 'thoiGianTao',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('KETQUA', 'thoiGianCapNhat',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint('KETQUA_maPhieuTraLoi_key', 'KETQUA', type_='unique')
    op.create_index(op.f('ix_KETQUA_maBaiKiemTra'), 'KETQUA', ['maBaiKiemTra'], unique=False)
    op.create_index(op.f('ix_KETQUA_maHocSinh'), 'KETQUA', ['maHocSinh'], unique=False)
    op.create_index(op.f('ix_KETQUA_maKetQua'), 'KETQUA', ['maKetQua'], unique=False)
    op.create_index(op.f('ix_KETQUA_maPhieuTraLoi'), 'KETQUA', ['maPhieuTraLoi'], unique=True)
    op.alter_column('LOPHOC', 'maToChuc',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('LOPHOC', 'maGiaoVienChuNhiem',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('LOPHOC', 'trangThai',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('LOPHOC', 'thoiGianTao',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('LOPHOC', 'thoiGianCapNhat',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index('idx_lophoc_gvcn', table_name='LOPHOC')
    op.drop_index('idx_lophoc_to_chuc', table_name='LOPHOC')
    op.create_index(op.f('ix_LOPHOC_maGiaoVienChuNhiem'), 'LOPHOC', ['maGiaoVienChuNhiem'], unique=False)
    op.create_index(op.f('ix_LOPHOC_maLopHoc'), 'LOPHOC', ['maLopHoc'], unique=False)
    op.create_index(op.f('ix_LOPHOC_maToChuc'), 'LOPHOC', ['maToChuc'], unique=False)
    op.drop_constraint('LOPHOC_maGiaoVienChuNhiem_fkey', 'LOPHOC', type_='foreignkey')
    op.drop_constraint('LOPHOC_maToChuc_fkey', 'LOPHOC', type_='foreignkey')
    op.create_foreign_key(None, 'LOPHOC', 'TOCHUC', ['maToChuc'], ['maToChuc'])
    op.create_foreign_key(None, 'LOPHOC', 'NGUOIDUNG', ['maGiaoVienChuNhiem'], ['maNguoiDung'])
    op.alter_column('MAUPHIEUTRALOI', 'coTuLuan',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('MAUPHIEUTRALOI', 'coThongTinHocSinh',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('MAUPHIEUTRALOI', 'coLogo',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('MAUPHIEUTRALOI', 'laMacDinh',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('MAUPHIEUTRALOI', 'laCongKhai',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('MAUPHIEUTRALOI', 'thoiGianTao',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('MAUPHIEUTRALOI', 'thoiGianCapNhat',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index('idx_mauphieu_author', table_name='MAUPHIEUTRALOI')
    op.drop_index('idx_mauphieu_org', table_name='MAUPHIEUTRALOI')
    op.create_index(op.f('ix_MAUPHIEUTRALOI_maMauPhieu'), 'MAUPHIEUTRALOI', ['maMauPhieu'], unique=False)
    op.create_index(op.f('ix_MAUPHIEUTRALOI_maNguoiTao'), 'MAUPHIEUTRALOI', ['maNguoiTao'], unique=False)
    op.create_index(op.f('ix_MAUPHIEUTRALOI_maToChuc'), 'MAUPHIEUTRALOI', ['maToChuc'], unique=False)
    op.alter_column('NGUOIDUNG', 'trangThai',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('NGUOIDUNG', 'thoiGianTao',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('NGUOIDUNG', 'thoiGianCapNhat',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint('NGUOIDUNG_email_key', 'NGUOIDUNG', type_='unique')
    op.drop_index('idx_nguoidung_tochuc', table_name='NGUOIDUNG')
    op.create_index(op.f('ix_NGUOIDUNG_email'), 'NGUOIDUNG', ['email'], unique=True)
    op.create_index(op.f('ix_NGUOIDUNG_maNguoiDung'), 'NGUOIDUNG', ['maNguoiDung'], unique=False)
    op.drop_constraint('NGUOIDUNG_maToChuc_fkey', 'NGUOIDUNG', type_='foreignkey')
    op.create_foreign_key(None, 'NGUOIDUNG', 'TOCHUC', ['maToChuc'], ['maToChuc'])
    op.alter_column('PHIEUTRALOI', 'daXuLyHoanTat',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('PHIEUTRALOI', 'thoiGianQuet',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('PHIEUTRALOI', 'thoiGianTao',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('PHIEUTRALOI', 'thoiGianCapNhat',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint('uq_phieu_unique', 'PHIEUTRALOI', type_='unique')
    op.create_index(op.f('ix_PHIEUTRALOI_maBaiKiemTra'), 'PHIEUTRALOI', ['maBaiKiemTra'], unique=False)
    op.create_index(op.f('ix_PHIEUTRALOI_maHocSinh'), 'PHIEUTRALOI', ['maHocSinh'], unique=False)
    op.create_index(op.f('ix_PHIEUTRALOI_maNguoiQuet'), 'PHIEUTRALOI', ['maNguoiQuet'], unique=False)
    op.create_index(op.f('ix_PHIEUTRALOI_maPhieuTraLoi'), 'PHIEUTRALOI', ['maPhieuTraLoi'], unique=False)
    op.alter_column('TAPTIN', 'maNguoiDung',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('TAPTIN', 'maToChuc',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('TAPTIN', 'thoiGianTao',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index('idx_taptin_thucthe', 'TAPTIN', ['thucTheNguon', 'maThucTheNguon'], unique=False)
    op.create_index(op.f('ix_TAPTIN_maNguoiDung'), 'TAPTIN', ['maNguoiDung'], unique=False)
    op.create_index(op.f('ix_TAPTIN_maTapTin'), 'TAPTIN', ['maTapTin'], unique=False)
    op.create_index(op.f('ix_TAPTIN_maToChuc'), 'TAPTIN', ['maToChuc'], unique=False)
    op.alter_column('THONGKEKIEMTRA', 'thoiGianTao',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('THONGKEKIEMTRA', 'thoiGianCapNhat',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint('uq_thongke_bkt_lop', 'THONGKEKIEMTRA', type_='unique')
    op.create_index(op.f('ix_THONGKEKIEMTRA_maBaiKiemTra'), 'THONGKEKIEMTRA', ['maBaiKiemTra'], unique=False)
    op.create_index(op.f('ix_THONGKEKIEMTRA_maLopHoc'), 'THONGKEKIEMTRA', ['maLopHoc'], unique=False)
    op.create_index(op.f('ix_THONGKEKIEMTRA_maThongKe'), 'THONGKEKIEMTRA', ['maThongKe'], unique=False)
    op.create_unique_constraint('uq_thongkekiemtra_mabkt_malop', 'THONGKEKIEMTRA', ['maBaiKiemTra', 'maLopHoc'])
    op.alter_column('TOCHUC', 'thoiGianTao',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('TOCHUC', 'thoiGianCapNhat',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_TOCHUC_maToChuc'), 'TOCHUC', ['maToChuc'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_TOCHUC_maToChuc'), table_name='TOCHUC')
    op.alter_column('TOCHUC', 'thoiGianCapNhat',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('TOCHUC', 'thoiGianTao',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint('uq_thongkekiemtra_mabkt_malop', 'THONGKEKIEMTRA', type_='unique')
    op.drop_index(op.f('ix_THONGKEKIEMTRA_maThongKe'), table_name='THONGKEKIEMTRA')
    op.drop_index(op.f('ix_THONGKEKIEMTRA_maLopHoc'), table_name='THONGKEKIEMTRA')
    op.drop_index(op.f('ix_THONGKEKIEMTRA_maBaiKiemTra'), table_name='THONGKEKIEMTRA')
    op.create_unique_constraint('uq_thongke_bkt_lop', 'THONGKEKIEMTRA', ['maBaiKiemTra', 'maLopHoc'])
    op.alter_column('THONGKEKIEMTRA', 'thoiGianCapNhat',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('THONGKEKIEMTRA', 'thoiGianTao',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('ix_TAPTIN_maToChuc'), table_name='TAPTIN')
    op.drop_index(op.f('ix_TAPTIN_maTapTin'), table_name='TAPTIN')
    op.drop_index(op.f('ix_TAPTIN_maNguoiDung'), table_name='TAPTIN')
    op.drop_index('idx_taptin_thucthe', table_name='TAPTIN')
    op.alter_column('TAPTIN', 'thoiGianTao',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('TAPTIN', 'maToChuc',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('TAPTIN', 'maNguoiDung',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_index(op.f('ix_PHIEUTRALOI_maPhieuTraLoi'), table_name='PHIEUTRALOI')
    op.drop_index(op.f('ix_PHIEUTRALOI_maNguoiQuet'), table_name='PHIEUTRALOI')
    op.drop_index(op.f('ix_PHIEUTRALOI_maHocSinh'), table_name='PHIEUTRALOI')
    op.drop_index(op.f('ix_PHIEUTRALOI_maBaiKiemTra'), table_name='PHIEUTRALOI')
    op.create_unique_constraint('uq_phieu_unique', 'PHIEUTRALOI', ['maBaiKiemTra', 'maHocSinh'])
    op.alter_column('PHIEUTRALOI', 'thoiGianCapNhat',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('PHIEUTRALOI', 'thoiGianTao',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('PHIEUTRALOI', 'thoiGianQuet',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('PHIEUTRALOI', 'daXuLyHoanTat',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_constraint(None, 'NGUOIDUNG', type_='foreignkey')
    op.create_foreign_key('NGUOIDUNG_maToChuc_fkey', 'NGUOIDUNG', 'TOCHUC', ['maToChuc'], ['maToChuc'], ondelete='CASCADE')
    op.drop_index(op.f('ix_NGUOIDUNG_maNguoiDung'), table_name='NGUOIDUNG')
    op.drop_index(op.f('ix_NGUOIDUNG_email'), table_name='NGUOIDUNG')
    op.create_index('idx_nguoidung_tochuc', 'NGUOIDUNG', ['maToChuc'], unique=False)
    op.create_unique_constraint('NGUOIDUNG_email_key', 'NGUOIDUNG', ['email'])
    op.alter_column('NGUOIDUNG', 'thoiGianCapNhat',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('NGUOIDUNG', 'thoiGianTao',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('NGUOIDUNG', 'trangThai',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.drop_index(op.f('ix_MAUPHIEUTRALOI_maToChuc'), table_name='MAUPHIEUTRALOI')
    op.drop_index(op.f('ix_MAUPHIEUTRALOI_maNguoiTao'), table_name='MAUPHIEUTRALOI')
    op.drop_index(op.f('ix_MAUPHIEUTRALOI_maMauPhieu'), table_name='MAUPHIEUTRALOI')
    op.create_index('idx_mauphieu_org', 'MAUPHIEUTRALOI', ['maToChuc'], unique=False)
    op.create_index('idx_mauphieu_author', 'MAUPHIEUTRALOI', ['maNguoiTao'], unique=False)
    op.alter_column('MAUPHIEUTRALOI', 'thoiGianCapNhat',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('MAUPHIEUTRALOI', 'thoiGianTao',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('MAUPHIEUTRALOI', 'laCongKhai',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('MAUPHIEUTRALOI', 'laMacDinh',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('MAUPHIEUTRALOI', 'coLogo',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('MAUPHIEUTRALOI', 'coThongTinHocSinh',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('MAUPHIEUTRALOI', 'coTuLuan',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_constraint(None, 'LOPHOC', type_='foreignkey')
    op.drop_constraint(None, 'LOPHOC', type_='foreignkey')
    op.create_foreign_key('LOPHOC_maToChuc_fkey', 'LOPHOC', 'TOCHUC', ['maToChuc'], ['maToChuc'], ondelete='CASCADE')
    op.create_foreign_key('LOPHOC_maGiaoVienChuNhiem_fkey', 'LOPHOC', 'NGUOIDUNG', ['maGiaoVienChuNhiem'], ['maNguoiDung'], ondelete='CASCADE')
    op.drop_index(op.f('ix_LOPHOC_maToChuc'), table_name='LOPHOC')
    op.drop_index(op.f('ix_LOPHOC_maLopHoc'), table_name='LOPHOC')
    op.drop_index(op.f('ix_LOPHOC_maGiaoVienChuNhiem'), table_name='LOPHOC')
    op.create_index('idx_lophoc_to_chuc', 'LOPHOC', ['maToChuc'], unique=False)
    op.create_index('idx_lophoc_gvcn', 'LOPHOC', ['maGiaoVienChuNhiem'], unique=False)
    op.alter_column('LOPHOC', 'thoiGianCapNhat',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('LOPHOC', 'thoiGianTao',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('LOPHOC', 'trangThai',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('LOPHOC', 'maGiaoVienChuNhiem',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('LOPHOC', 'maToChuc',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_index(op.f('ix_KETQUA_maPhieuTraLoi'), table_name='KETQUA')
    op.drop_index(op.f('ix_KETQUA_maKetQua'), table_name='KETQUA')
    op.drop_index(op.f('ix_KETQUA_maHocSinh'), table_name='KETQUA')
    op.drop_index(op.f('ix_KETQUA_maBaiKiemTra'), table_name='KETQUA')
    op.create_unique_constraint('KETQUA_maPhieuTraLoi_key', 'KETQUA', ['maPhieuTraLoi'])
    op.alter_column('KETQUA', 'thoiGianCapNhat',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('KETQUA', 'thoiGianTao',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(None, 'HOCSINH', type_='foreignkey')
    op.create_foreign_key('HOCSINH_maLopHoc_fkey', 'HOCSINH', 'LOPHOC', ['maLopHoc'], ['maLopHoc'], ondelete='CASCADE')
    op.drop_constraint('uq_hocsinh_mahocsinhtruong_malophoc', 'HOCSINH', type_='unique')
    op.drop_index(op.f('ix_HOCSINH_maLopHoc'), table_name='HOCSINH')
    op.drop_index(op.f('ix_HOCSINH_maHocSinhTruong'), table_name='HOCSINH')
    op.drop_index(op.f('ix_HOCSINH_maHocSinh'), table_name='HOCSINH')
    op.create_unique_constraint('uq_hocsinh_code_lop', 'HOCSINH', ['maHocSinhTruong', 'maLopHoc'])
    op.create_index('idx_hocsinh_lop', 'HOCSINH', ['maLopHoc'], unique=False)
    op.alter_column('HOCSINH', 'thoiGianCapNhat',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('HOCSINH', 'thoiGianTao',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('HOCSINH', 'trangThai',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('HOCSINH', 'maLopHoc',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_index(op.f('ix_DAPAN_maDapAn'), table_name='DAPAN')
    op.drop_index(op.f('ix_DAPAN_maBaiKiemTra'), table_name='DAPAN')
    op.create_unique_constraint('DAPAN_maBaiKiemTra_key', 'DAPAN', ['maBaiKiemTra'])
    op.alter_column('DAPAN', 'thoiGianCapNhat',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('DAPAN', 'thoiGianTao',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('DAPAN', 'maBaiKiemTra',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_constraint('uq_caidat_matochuc_tukhoa', 'CAIDAT', type_='unique')
    op.drop_index(op.f('ix_CAIDAT_maToChuc'), table_name='CAIDAT')
    op.drop_index(op.f('ix_CAIDAT_maCaiDat'), table_name='CAIDAT')
    op.create_unique_constraint('uq_caidat_org_key', 'CAIDAT', ['maToChuc', 'tuKhoa'])
    op.alter_column('CAIDAT', 'thoiGianCapNhat',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('CAIDAT', 'thoiGianTao',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('CAIDAT', 'maToChuc',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_constraint('uq_baikiemtra_lophoc', 'BAIKIEMTRA_LOPHOC', type_='unique')
    op.drop_index(op.f('ix_BAIKIEMTRA_LOPHOC_maLopHoc'), table_name='BAIKIEMTRA_LOPHOC')
    op.drop_index(op.f('ix_BAIKIEMTRA_LOPHOC_maBaiKiemTra'), table_name='BAIKIEMTRA_LOPHOC')
    op.drop_index(op.f('ix_BAIKIEMTRA_LOPHOC_id'), table_name='BAIKIEMTRA_LOPHOC')
    op.create_unique_constraint('uq_bkt_lop', 'BAIKIEMTRA_LOPHOC', ['maBaiKiemTra', 'maLopHoc'])
    op.alter_column('BAIKIEMTRA_LOPHOC', 'thoiGianTao',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('BAIKIEMTRA_LOPHOC', 'maLopHoc',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('BAIKIEMTRA_LOPHOC', 'maBaiKiemTra',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_constraint(None, 'BAIKIEMTRA', type_='foreignkey')
    op.drop_constraint(None, 'BAIKIEMTRA', type_='foreignkey')
    op.drop_constraint(None, 'BAIKIEMTRA', type_='foreignkey')
    op.create_foreign_key('BAIKIEMTRA_maNguoiTao_fkey', 'BAIKIEMTRA', 'NGUOIDUNG', ['maNguoiTao'], ['maNguoiDung'], ondelete='CASCADE')
    op.create_foreign_key('BAIKIEMTRA_maToChuc_fkey', 'BAIKIEMTRA', 'TOCHUC', ['maToChuc'], ['maToChuc'], ondelete='CASCADE')
    op.create_foreign_key('BAIKIEMTRA_maMauPhieu_fkey', 'BAIKIEMTRA', 'MAUPHIEUTRALOI', ['maMauPhieu'], ['maMauPhieu'], ondelete='CASCADE')
    op.drop_index(op.f('ix_BAIKIEMTRA_maToChuc'), table_name='BAIKIEMTRA')
    op.drop_index(op.f('ix_BAIKIEMTRA_maNguoiTao'), table_name='BAIKIEMTRA')
    op.drop_index(op.f('ix_BAIKIEMTRA_maMauPhieu'), table_name='BAIKIEMTRA')
    op.drop_index(op.f('ix_BAIKIEMTRA_maBaiKiemTra'), table_name='BAIKIEMTRA')
    op.create_index('idx_bkt_org', 'BAIKIEMTRA', ['maToChuc'], unique=False)
    op.create_index('idx_bkt_author', 'BAIKIEMTRA', ['maNguoiTao'], unique=False)
    op.alter_column('BAIKIEMTRA', 'thoiGianCapNhat',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('BAIKIEMTRA', 'thoiGianTao',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('BAIKIEMTRA', 'trangThai',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'nhap'::character varying"))
    op.alter_column('BAIKIEMTRA', 'laDeTongHop',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('BAIKIEMTRA', 'maMauPhieu',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('BAIKIEMTRA', 'maNguoiTao',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('BAIKIEMTRA', 'maToChuc',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_index(op.f('ix_CAIDATLOPHOC_maLopHoc'), table_name='CAIDATLOPHOC')
    op.drop_table('CAIDATLOPHOC')
    # ### end Alembic commands ### 